### ISSUE TITLE
Orderable support

### ISSUE THREAD

**Issue by emilyhorsman** [wagtail/wagtail-autocomplete#5]

**Comment by rwicklin** [comment]
Going to be taking a look at this issue, as I'd like to use this functionality. Will submit a PR when and if it comes to anything

**Comment by kutenai** [comment]
Any update on this? Was trying to get this to work.. but no joy. Probably since I'm using it to choose a model from inside an orderable.
```python
class Gardener(Orderable):
    garden = ParentalKey(FeaturedGardenPage, on_delete=models.CASCADE,
                         related_name='gardeners')
    gardener = models.ForeignKey('gardenbuzz_profile.GardenerProfile',
                                 on_delete=models.CASCADE,
                                 related_name='gardens')

    comment_notify = models.BooleanField()
    comment_respond = models.BooleanField()

    panels = [
        AutocompletePanel('gardener',
                          page_type='gardenbuzz_profile.GardenerProfile',
                          is_single=True),
        MultiFieldPanel([
            FieldPanel('comment_notify'),
            FieldPanel('comment_respond'),
        ], heading='Comments', classname='collapsible collapsed')
    ]
```

Where the GardenerProfile is NOT a page model. 

I get no errors, but my admin page has no input
![2018-10-05_16-04-55](https://user-images.githubusercontent.com/1226809/46562268-7ce94480-c8b8-11e8-9f21-5748dea84b16.png)

**Comment by harrislapiroff** [comment]
The solution we've just merged (inline support, basically) actually isn't what I meant when I vaguely said "Orderable Support" but it's clearly how most people interpreted this ticket and was a necessary change, so I'm going to close this ticket and open a new one that is more specific 😝
